### ISSUE TITLE
The site does not seem to update the deployment

### ISSUE THREAD

**Issue by hexiaokang** [reactjs/zh-hans.reactjs.org#1029]
中文：https://zh-hans.reactjs.org/community/team.html
原文：https://reactjs.org/community/team.html
成员数量、排序、照片等差异比较大。

**Comment by K4Lok** [comment]
Hi @QC-L , @hexiaokang 
I've pulled the latest version and found the contents are actually the same. 

Is it probably because the production test didn't pass, and the server used the previously passed build?

<img width="507" alt="Screenshot 2023-02-14 at 6 33 59 PM" src="https://user-images.githubusercontent.com/82365010/218710600-6604505a-9dcc-476a-881e-3d785ddbfca2.png">
