### ISSUE TITLE
别为了翻译而翻译，请不要啰嗦，请不要学院派，这不是制造火箭

### ISSUE THREAD

**Issue by buuug7** [reactjs/zh-hans.reactjs.org#166]
别为了翻译而翻译，请不要啰嗦，不要学院派，这不是制造火箭，快速行动，在逐步改善，中文文档居然还在翻译当中，这谁把的关？44个PR都已经等待多时了。咬文嚼字请别用错方向，React在快速迭代中，文档要与时俱进，你扣字眼只会导致进度完全被拉下来，按照目前该仓库的PR的审核速度，被React甩的会越来越远。  

请遵守KISS，而贡献者由于考虑诸多不必要的事情，繁琐，繁琐，繁琐，导致很多人失去贡献的兴趣。  

我要说的请保持快速行动，别再锯纸削。把一个事情搞复杂是一件简单的事，但要把一个复杂的事变简单，这是一件复杂的事。

**Comment by dear-lizhihua** [comment]
没人欠你的

**Comment by QC-L** [comment]
如果需要看完整的，可以先去看 https://react.docschina.org。
此次翻译我会保证质量。如果你想参与，非常欢迎。但如果你只是说说，那还请耐心等待。

**Comment by cyan33** [comment]
Hi @buuug7, while I understand your concern and it's true that the progress of translation hasn't been going very quickly, we should also be aware that the reviewers of this repo are volunteering/sacrificing their own time after work to contribute to the community. By that, I think we all should be grateful for all the work that has been done so far. Toxic words should **never** go into this community and will **not** help we progress.

As for the translation, I've been in the translation group chat for some while. **Translation is hard.** Especially when it comes to **wording**. I think that comes along with the fact that we're human, not machines. When I interned at the React team, my first bootcamp task there was to add a warning message on the deprecated usage of React context. I didn't expect my colleagues to spend massive amount of time reviewing my change, since it's just ONE sentence. But they did. And we went back and forth until we finally all agree that this message is exactly what we want to deliver to developers, not to confuse them in any ways.

Later when I worked on documenting suspense inside Facebook, the reviewing process went even more harder. All of our team know exactly **wording is critically important**. We never want engineers in Facebook feel overwhelmed and confused when reading the doc, which could comes with just a mere inappropriate wording. I should also confess that sometimes it took even more time to work on the document, rather than implement the feature itself.

Years ago when I started out learning React, I didn't have much good resources. Honestly speaking, the Chinese translation was so confusing, to an extent that I had to switch to the English version. Even now, I sometimes ask myself if it's really because the Chinese language itself is bad at documenting, or is it because we, as translators, spent less energy and time on wording.

This is of course not **building rocket**. But keep in mind that in China we have millions of developers. Each page of translation might reach to tens of thousands of them. I wish I had chance to a well-formatted and translated document in the first place. If we can grab this chance and improve on the translation, why shouldn't the time be NOW?

We welcome all Chinese developers to join the translation, if you really want to dedicate your time on giving back to the community. We also welcome any reasonable suggestions on how you think we could speed up the translation progress and improve on wording. **But if you don't have the time to do so, or not willing to, the basic line is at least to show appropriate amount of respect.**

Here I want to give a huge shoutout to all maintainers, reviewers, and contributors in the translation of the React document. Without you we couldn't have done anything, and all our Chinese developers would lack the chance to see the latest docs of React. Thank you so much ❤️
